name: Domain Configuration UI
description: 'Allows saving of domain specific configuration through the administrative interface.'
type: module
package: Domain
core_version_requirement: ^9 || ^10 || ^11
configure: domain_config_ui.settings
dependencies:
  - domain:domain_config

# Information added by Drupal.org packaging script on 2024-09-18
version: '2.0.0-beta2'
project: 'domain'
datestamp: 1726699794
