domain_simple_sitemap.settings:
  type: config_object
  label: 'Domain simple sitemap settings'
  mapping:
    domain_simple_sitemap_filter:
      type: boolean
      label: 'Use node source instead of node access as filter'
    domain_simple_sitemap_replace_homepage:
      type: boolean
      label: 'Replace default front page URL to base domain URL'
