name: Domain Configuration
description: 'Allows domain specific configuration.'
type: module
package: Domain
# version: VERSION
core_version_requirement: ^9 || ^10 || ^11
dependencies:
  - domain:domain

# Information added by Drupal.org packaging script on 2024-09-18
version: '2.0.0-beta2'
project: 'domain'
datestamp: 1726699794
